// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2019-08-10 20:24:55.018824405 +0800 CST m=+0.097760396

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://google.com",
        "contact": {
            "name": "Neil_Hsieh",
            "url": "https://google.com",
            "email": "neil605164@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/backend/upload_video": {
            "post": {
                "description": "上傳 mp4 影片",
                "produces": [
                    "multipart/form-data"
                ],
                "tags": [
                    "Video"
                ],
                "summary": "上傳影片",
                "parameters": [
                    {
                        "type": "file",
                        "description": "影片檔",
                        "name": "video",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/structs.APIResult"
                        }
                    },
                    "400": {
                        "description": "異常錯誤",
                        "schema": {
                            "$ref": "#/definitions/structs.APIResult"
                        }
                    }
                }
            }
        },
        "/test/error_task": {
            "get": {
                "description": "DB Pool 測試錯誤發生時是否可以回傳正確的 logID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Test"
                ],
                "summary": "測試錯誤發生時是否可以回傳正確的 logID",
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/structs.APIResult"
                        }
                    },
                    "400": {
                        "description": "異常錯誤",
                        "schema": {
                            "$ref": "#/definitions/structs.APIResult"
                        }
                    }
                }
            }
        },
        "/test/get_redis": {
            "get": {
                "description": "Redis Pool 連線測試",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Test"
                ],
                "summary": "測試 Redis 取值",
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/structs.APIResult"
                        }
                    },
                    "400": {
                        "description": "異常錯誤",
                        "schema": {
                            "$ref": "#/definitions/structs.APIResult"
                        }
                    }
                }
            }
        },
        "/test/ping_db_once": {
            "get": {
                "description": "DB Pool 連線測試",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Test"
                ],
                "summary": "Ping DB 測試",
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/structs.APIResult"
                        }
                    },
                    "400": {
                        "description": "異常錯誤",
                        "schema": {
                            "$ref": "#/definitions/structs.APIResult"
                        }
                    }
                }
            }
        },
        "/test/ping_db_second": {
            "get": {
                "description": "DB Pool 連線測試",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Test"
                ],
                "summary": "Ping DB 測試",
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/structs.APIResult"
                        }
                    },
                    "400": {
                        "description": "異常錯誤",
                        "schema": {
                            "$ref": "#/definitions/structs.APIResult"
                        }
                    }
                }
            }
        },
        "/test/set_redis": {
            "post": {
                "description": "Redis Pool 連線測試",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Test"
                ],
                "summary": "測試 Redis 存值",
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/structs.APIResult"
                        }
                    },
                    "400": {
                        "description": "異常錯誤",
                        "schema": {
                            "$ref": "#/definitions/structs.APIResult"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "structs.APIResult": {
            "type": "object",
            "properties": {
                "error_code": {
                    "type": "integer"
                },
                "error_msg": {
                    "type": "string"
                },
                "log_id": {
                    "type": "string"
                },
                "result": {
                    "type": "object"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "127.0.0.1:9999",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "上傳影片",
	Description: "上傳影片練習用",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
