basePath: /
definitions:
  structs.APIResult:
    properties:
      error_code:
        type: integer
      error_msg:
        type: string
      log_id:
        type: string
      result:
        type: object
    type: object
host: localhost:9999
info:
  contact:
    email: neil605164@gmail.com
    name: Neil_Hsieh
    url: https://google.com
  description: 上傳影片練習用
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://google.com
  title: 上傳影片
  version: "1.0"
paths:
  /backend/upload_video:
    post:
      consumes:
      - multipart/form-data
      description: 上傳 mp4 影片
      parameters:
      - description: 影片檔
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/structs.APIResult'
        "400":
          description: 異常錯誤
          schema:
            $ref: '#/definitions/structs.APIResult'
      summary: 上傳影片
      tags:
      - Video
  /test/error_task:
    get:
      description: DB Pool 測試錯誤發生時是否可以回傳正確的 logID
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/structs.APIResult'
        "400":
          description: 異常錯誤
          schema:
            $ref: '#/definitions/structs.APIResult'
      summary: 測試錯誤發生時是否可以回傳正確的 logID
      tags:
      - Test
  /test/get_redis:
    get:
      description: Redis Pool 連線測試
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/structs.APIResult'
        "400":
          description: 異常錯誤
          schema:
            $ref: '#/definitions/structs.APIResult'
      summary: 測試 Redis 取值
      tags:
      - Test
  /test/ping_db_once:
    get:
      description: DB Pool 連線測試
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/structs.APIResult'
        "400":
          description: 異常錯誤
          schema:
            $ref: '#/definitions/structs.APIResult'
      summary: Ping DB 測試
      tags:
      - Test
  /test/ping_db_second:
    get:
      description: DB Pool 連線測試
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/structs.APIResult'
        "400":
          description: 異常錯誤
          schema:
            $ref: '#/definitions/structs.APIResult'
      summary: Ping DB 測試
      tags:
      - Test
  /test/set_redis:
    post:
      description: Redis Pool 連線測試
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/structs.APIResult'
        "400":
          description: 異常錯誤
          schema:
            $ref: '#/definitions/structs.APIResult'
      summary: 測試 Redis 存值
      tags:
      - Test
swagger: "2.0"
